version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - backend
      
  api_server:
    build: 
     context: .
    container_name: kafka_demo
    restart: on-failure:5
    ports:
      - 3000:3000
    depends_on:
      - zookeeper
      - kafka
    networks:
      - backend
    links:
      - zookeeper
      - kafka
networks:
  backend:
   driver: bridge